
const timeTitles = [
    "Atomic Habits",
    "The Power of Habit",
    "Deep Work",
    "12 Rules for Life",
    "Think and Grow Rich",
    "Rich Dad, Poor Dad",
    "Man's Search for Meaning",
    "The 4-Hour Work Week",
    "Getting Things Done",
    "Mindset",
    "Outliers",
    "Can't Hurt Me",
    "Eat That Frog",
    "Make Your Bed",
    "Awaken The Giant Within",
    "Flow",
    "The Obstacle Is the Way",
    "The Power of Your Subconscious Mind",
    "The Willpower Instinct",
    "Four Thousand Weeks",
    "Why We Sleep",
    "The 5 AM Club",
    "The Compound Effect & The Tipping Point",
    "Mastery",
    "Drive",
    "Make Time",
    "Smarter Faster Better",
    "Range",
    "The Art of Thinking Clearly",
    "The Success Principles",
    "The Bullet Journal Method",
];
const intellectTitles = [
    "A Mind for Numbers",
    "Black Box Thinking",
    "Blink",
    "Do Not Make Me Think",
    "Essentialism",
    "Fluent Forever",
    "Fluent in 3 Months",
    "How To Not Be Wrong",
    "How To Take Smart Notes",
    "How To Think Like a Roman Emperor",
    "How To Think Like Leonardo Da Vinci",
    "How To Think",
    "How We Learn",
    "Learn Like Einstein",
    "Learning How To Learn",
    "Limitless",
    "Make It Stick",
    "Moonwalking With Einstein",
    "Peak",
    "Six Thinking Hats",
    "The 5 Elements of Effective Thinking",
    "The Art of Learning",
    "The Art of Thinking Clearly",
    "The First 20 Hours",
    "The Organized Mind",
    "The Talent Code",
    "Thinking Like a Freak",
    "Thinking Fast and Slow",
    "Thinking in Systems",
    "Thinking Straight",
    "This Will Make You Smarter",
    "Unlimited Memory"
];
const othersTitles = [
    "Crucial Conversations",
    "Dark Psychology 101",
    "Drive",
    "Emotional Intelligence",
    "Games People Play",
    "Getting To Yes",
    "How To Talk To Anyone",
    "How To Win Friends and Influence People",
    "How We Decide",
    "Influence",
    "Influencer",
    "Just Listen",
    "Never Split The Difference",
    "Predictably Irrational",
    "Presuasion",
    "Surrounded By Idiots",
    "Talking To Strangers",
    "The Art Of Communication",
    "The Art Of Seduction",
    "The Body Keeps The Score",
    "The Fine Art Of Small Talk",
    "The Interpretation Of Dreams",
    "The Laws Of Human Nature",
    "The Like Switch",
    "What Every Body Is Saying"
];

const programmingTitles = [
    "Agile Methodology",
    "AI",
    "Back-end",
    "Basic Programming Concepts",
    "C Syntax",
    "CS Attributes",
    "C++ Syntax",
    "Cloud-native App",
    "Data Science",
    "Front-end",
    "Git & GitHub",
    "Java Attributes",
    "Java Concepts",
    "Java Syntax",
    "Laravel",
    "Material Design Concepts",
    "Mobile App Architecture",
    "Mobile App Deployment and Distribution",
    "Mobile App Dev Concepts",
    "Mobile App Storage",
    "Networking",
    "NLP",
    "PHP Attributes",
    "PHP Concept Purpose",
    "PHP Concepts",
    "PHP Syntax",
    "Programming Concepts",
    "React JS",
    "Software Design",
    "Software Development",
    "Software Engineer",
    "Software Project Management",
    "Software Testing",
    "Terminology",
    "UML",
    "User Experience Design",
    "User Interface Design",
    "Version Control",
    "Video Game Level Design",
    "Video Game Mechanics",
    "Video Game Narrative Design",
];
